#!/usr/bin/env python

'''
NAME
    ht - (headtail) output the beginning and ending of files

SYNOPSIS
    ht [OPTION]... [FILE]...

    Print the beginning and ending of each file.
    Prints '...' for omitted lines.
    Defaults to first 10 and last 10 lines.
    Standard input may be specified by - argument.
    If no files are specified, uses standard input.

    Prints header lines if more than one file.
        Prints a blank line between output of multiple files.

OPTIONS
    n is a non-negative integer in the following options,
    except for the first n in -n n.

    -n, --lines=n, -n n
        Specify the number of lines from beginning and end of file to print.
        In the -n n option, the first n is literal, the second is the number.

    --head-lines=n
        Specify the number of lines from beginning of file to print.

    --tail-lines=n
        Specify the number of lines from end of file to print.

    -v, --verbose
        Print headers.

    -q, --quiet, --silent
        Do not print headers.

    --help
        Show this and quit.

EXAMPLES
    ls -ltr ~ | ht -20
        Shows first 20 and last 20 lines of output of previous command.

    ht --head-lines=1 --tail-lines=3 *.py
        Shows first line and last three lines of each *.py file.

LICENSE

    Copyright (c) 2016 James Prior, Andrew Kubera

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use,
    copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following
    conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.
'''

from __future__ import print_function

import re
import sys
from itertools import islice
from collections import deque
from argparse import ArgumentParser

DEFAULT_N_LINES = 10


def cli_arg_parser():
    '''Returns the command line ArgumentParser object'''
    parser = ArgumentParser('ht',
                            description='(headtail) output the beginning and ending of files',
                            )
    parser.add_argument('-v', '--verbose',
                        action='store_true',
                        help='Print headers')
    parser.add_argument('-q', '--quiet',
                        action='store_false',
                        dest='verbose',
                        help='Do not print headers.')
    parser.add_argument('-n', '--lines',
                        type=int,
                        default=10,
                        help='Specify the number of lines from beginning and end of file to '
                             'print. In the -n n option, the first n is literal, the second '
                             'is the number.')
    parser.add_argument('--head-lines',
                        type=int,
                        nargs='?',
                        help='Specify the number of lines from beginning of file to print.')
    parser.add_argument('--tail-lines',
                        type=int,
                        nargs='?',
                        help='Specify the number of lines from end of file to print.')
    parser.add_argument('filenames',
                        type=str,
                        nargs='*',
                        default=['-'],
                        help='''Print the beginning and ending of each file. Prints '...' for
                                omitted lines. Defaults to first 10 and last 10 lines.
                                Standard input may be specified by - argument.
                                If no files are specified, uses standard input.''')

    return parser


def do_file(f, n_head_lines, n_tail_lines):
    f = iter(f)
    for line in islice(f, n_head_lines):
        print(line, end='')

    tail_lines = deque(f, n_tail_lines+1)
    if len(tail_lines) > n_tail_lines:
        print('...')
        tail_lines.popleft()
    for line in tail_lines:
        print(line, end='')


def show_header(show_filename, filename, i):
    if not show_filename:
        return

    if i > 0:
        print()
    print('==> %s <==' % filename)


def parse_command_line_args(argv):
    """
    Normalizes shorthand arguments and sends result to the parser
    returned by cli_arg_parser(). This returns the resulting namespace
    object.
    """
    # match the first shorthand lines argument (eg. -3) and expand to -n flag (-n3)
    arg_re = re.compile(r'\-[0-9]+')
    matching_args = (i for i, x in enumerate(argv) if arg_re.match(x))
    # find first index matching the regex, or None
    idx = next(matching_args, None)
    if idx is not None:
        # we have a match: substitute -X with -nX
        argv[idx] = '-n' + argv[idx][1:]
    args = cli_arg_parser().parse_args(argv[1:])
    return args


def main(argv, stdin):
    args = parse_command_line_args(argv)
    n_head_lines = args.head_lines if args.head_lines is not None else args.lines
    n_tail_lines = args.tail_lines if args.tail_lines is not None else args.lines

    for i, filename in enumerate(args.filenames):
        if filename == '-':
            f = stdin
            filename = 'standard input'
        else:
            f = open(filename)
        show_header(args.verbose, filename, i)
        do_file(f, n_head_lines, n_tail_lines)


if __name__ == '__main__':
    main(sys.argv, sys.stdin)
