#!/usr/bin/env python

'''
NAME
    ht - (headtail) output the beginning and ending of files

SYNOPSIS
    ht [OPTION]... [FILE]...

    Print the beginning and ending of each file.
    Prints '...' for omitted lines.
    Defaults to first 10 and last 10 lines.
    Standard input may be specified by - argument.
    If no file is specified, uses standard input.

    Prints header lines if more than one file.
        Prints a blank line between output of multiple files.

OPTIONS
    -n, --lines=n
        Specify the number of lines from beginning and end of file to print.

    --head-lines=n
        Specify the number of lines from beginning of file to print.

    --tail-lines=n
        Specify the number of lines from end of file to print.

    -v, --verbose
        Print headers.

    -q, --quiet, --silent
        Do not print headers.

    --help
        Show this and quit.

EXAMPLES
    ls -ltr ~ | ht -20
        Shows first 20 and last 20 lines of output of previous command.

    ht --head-lines=1 --tail-lines=3 *.py
        Shows first line and last three lines of each *.py file.

LICENSE

    Copyright (c) 2016 James Prior

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use,
    copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following
    conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.
'''

from __future__ import print_function
from sys import stdin
from itertools import islice
from collections import deque
import click


def do_file(f, n_head_lines, n_tail_lines):

    f = iter(f)
    for line in islice(f, n_head_lines):
        print(line, end='')

    tail_lines = deque(f, n_tail_lines+1)
    if len(tail_lines) > n_tail_lines:
        print('...')
        tail_lines.popleft()
    for line in tail_lines:
        print(line, end='')

def show_header(show_filename, filename, i):
    if not show_filename:
        return

    if i > 0:
        print()
    print('==> %s <==' % filename.name)

@click.command()
@click.option('-n', '--lines', default=10, help='Specify the number of lines from beginning and end of file to print.')
@click.option('--head-lines', default=10, help='Specify the number of lines from beginning of file to print.')
@click.option('--tail-lines', default=10, help='Specify the number of lines from end of file to print.')
@click.option('-v','--verbose', 'headers', flag_value='verbose', help='Print headers.')
@click.option('-q', '--quiet', '--silent', 'headers', flag_value='quiet', help ='Do not print headers.')
@click.argument('files', nargs=-1,type=click.File('r'))
def main(lines, head_lines, tail_lines, headers, files):

    # determine number of lines
    if lines != 10:
        n_head_lines = lines
        n_tail_lines = lines
    else:
        n_head_lines = head_lines
        n_tail_lines = tail_lines

    # determine desirability of headers
    forbid_headers = False
    require_headers = False
    if headers == 'verbose':
        require_headers = True
    elif headers == 'quiet':
        forbid_headers = True

    filenames = []
    if files is not None:
        for filewrapper in files:
            filenames.append(filewrapper)

    assert not (forbid_headers and require_headers)
    show_headers = (
        (len(filenames) > 1 or require_headers)
        and not forbid_headers)

    if not filenames:
        filenames.append('-')

    for i, filename in enumerate(filenames):
        if filename == '-':
            f = stdin
            filename = 'standard input'
        else:
            f = filename
        show_header(show_headers, filename, i)
        do_file(f, n_head_lines, n_tail_lines)

if __name__ == '__main__':
    main()
