#!/usr/bin/env python

'''
NAME
    ht - (headtail) output the beginning and ending of files

SYNOPSIS
    ht [OPTION]... [FILE]...

    Print the beginning and ending of each file.
    Prints '...' for omitted lines.
    Defaults to first 10 and last 10 lines.
    Standard input may be specified by - argument.
    If no files are specified, uses standard input.

    Prints header lines if more than one file.
        Prints a blank line between output of multiple files.

OPTIONS
    n is a non-negative integer in the following options,
    except for the first n in -n n.

    -n, --lines=n, -n n
        Specify the number of lines from beginning and end of file to print.
        In the -n n option, the first n is literal, the second is the number.

    --head-lines=n
        Specify the number of lines from beginning of file to print.

    --tail-lines=n
        Specify the number of lines from end of file to print.

    -v, --verbose
        Print headers.

    -q, --quiet, --silent
        Do not print headers.

    --help
        Show this and quit.

EXAMPLES
    ls -ltr ~ | ht -20
        Shows first 20 and last 20 lines of output of previous command.

    ht --head-lines=1 --tail-lines=3 *.py
        Shows first line and last three lines of each *.py file.

LICENSE

    Copyright (c) 2016 James Prior

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use,
    copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following
    conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.
'''

from __future__ import print_function
import sys
import re
from itertools import islice
from collections import deque
from os.path import basename

DEFAULT_N_LINES = 10


def get_usage():
    '''Returns usage as multi-line string.

    Automatically uses name of program as executed,
    so usage is still correct after renaming program.'''
    program_name = basename(sys.argv[0])
    return re.sub(r'\bht\b', program_name, __doc__)


def complain_and_quit(error_message=None):
    messages = []
    if error_message:
        messages.append('ERROR: %s' % error_message)
    messages.append(get_usage())
    s = '\n'.join(messages)
    sys.exit(s)


def do_file(f, n_head_lines, n_tail_lines):
    f = iter(f)
    for line in islice(f, n_head_lines):
        print(line, end='')

    tail_lines = deque(f, n_tail_lines+1)
    if len(tail_lines) > n_tail_lines:
        print('...')
        tail_lines.popleft()
    for line in tail_lines:
        print(line, end='')


def show_header(show_filename, filename, i):
    if not show_filename:
        return

    if i > 0:
        print()
    print('==> %s <==' % filename)


def parse_arguments(argv):
    n_head_lines = DEFAULT_N_LINES
    n_tail_lines = DEFAULT_N_LINES

    forbid_headers = False
    require_headers = False

    number_argument_pattern = re.compile(r'^(-|--lines=)(?P<n>\d+)$')
    n_head_lines_pattern = re.compile(r'^--head-lines=(?P<n>\d+)$')
    n_tail_lines_pattern = re.compile(r'^--tail-lines=(?P<n>\d+)$')

    filenames = []
    args = iter(argv[1:])
    for arg in args:
        if arg == '--help':
            print(__doc__)
            return
        if arg == '-':
            filenames.append(arg)
            continue
        if arg in ('-v', '--verbose',):
            require_headers = True
            continue
        if arg in ('-q', '--quiet', '--silent'):
            forbid_headers = True
            continue
        if arg == '-n':
            n = int(next(args))
            n_head_lines = n
            n_tail_lines = n
            continue
        m = re.match(number_argument_pattern, arg)
        if m:
            n = int(m.group('n'))
            n_head_lines = n
            n_tail_lines = n
            continue
        m = re.match(n_head_lines_pattern, arg)
        if m:
            n = int(m.group('n'))
            n_head_lines = n
            continue
        m = re.match(n_tail_lines_pattern, arg)
        if m:
            n = int(m.group('n'))
            n_tail_lines = n
            continue
        filenames.append(arg)


    if forbid_headers and require_headers:
        complain_and_quit('Specified both verbose and quiet options.')
    show_headers = (
        (len(filenames) > 1 or require_headers)
        and not forbid_headers)

    if not filenames:
        filenames.append('-')

    return n_head_lines, n_tail_lines, show_headers, filenames


def main(argv, stdin):
    n_head_lines, n_tail_lines, show_headers, filenames = parse_arguments(argv)

    for i, filename in enumerate(filenames):
        if filename == '-':
            f = stdin
            filename = 'standard input'
        else:
            f = open(filename)
        show_header(show_headers, filename, i)
        do_file(f, n_head_lines, n_tail_lines)


if __name__ == '__main__':
    main(sys.argv, sys.stdin)
